version: '3'

services:

  docker-mysql:
    container_name: docker-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: menu
      MYSQL_ROOT_PASSWORD: abc123
    expose:
      - 3306
    ports:
      - 3308:3306
    networks:
      - menu-network
    restart: always

  menu-api:
    restart: on-failure
    container_name: menu-api
    build:
      context: .
      dockerfile: Dockerfile
    image: menu-api:latest
    expose:
      - 8090
    ports:
      - 8090:8090
    networks:
      - menu-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/menu?allowPublicKeyRetrieval=true
    depends_on:
      - docker-mysql

networks:
  menu-network:
    driver: bridge